--- 

- name: manage user
  become: yes
  become_user: root
  user:
      name: "{{ item.user_name }}"
      shell: "{{ item.shell }}"
      state: "{{ item.user_state }}"
      remove: "{{ item.user_bool }}"
      append: yes
      groups: "{{ item.user_groups|join(',') if item.user_groups is defined else ''}}"
  with_items:
      - "{{ users_list }}"

- name: ensure ssh key added
  become: yes
  become_user: root
  authorized_key:
      user: "{{ item.user_name }}"
      state: "{{ item.user_state }}"
      key: "{{ item.pub_key_list|join('\n') if item.pub_key_list is defined else ''}}"
  with_items:
      - "{{ users_list }}"
  when:
      - item.user_state == 'present'

- name: ensure sudo install
  become: yes
  become_user: root
  apt:
      name: sudo
      state: present

- name: ensure /etc/sudoers.d include
  become: yes
  become_user: root
  lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: "#includedir /etc/sudoers.d"
      line: "includedir /etc/sudoers.d"

- name: ensure ansible_sudoers file present
  become: yes
  become_user: root
  template:
      src: ansible_sudoers.j2
      dest: /etc/sudoers/ansible_sudoers
      owner: root
      group: root


