mangle:
    {prerouting_policy: "ACCEPT",
    input_policy: "ACCEPT",
    forward_policy: "ACCEPT",
    output_policy: "ACCEPT",
    postrouting_policy: "ACCEPT"}

filter:
    {input_policy: "ACCEPT",
    forward_policy: "DROP",
    output_policy: "ACCEPT"}

docker_bool: "True"

iptables_rules_path: iptables.up.rules.j2
iptables_rules_recovery: iptables_recovery.j2

allowed:
    - { port: 22, protocol: 'tcp', source: 0/0, name: 'ssh' }
    - { port: 80, protocol: 'tcp', source: 0/0, name: 'http' }
    - { port: 443, protocol: 'tcp', source: 0/0, name: 'https' }
    - { port: 8080, protocol: 'tcp', source: 0/0, name: 'jenkins' }



