---

- name: ensure iptables install
  apt:
      name: "{{ item }}"
      state: present
  with_items:
      - iptables
      - iptables-persistent

- name: ensure ufw disabled
  become: yes
  become_user: root
  ufw:
      state: disabled
  ignore_errors: yes

- name: ensure ufw absent in system
  become: yes
  become_user: root
  apt:
      name: ufw
      state: absent
      purge: yes

- name: ensure rules.v4 file absent
  become: yes
  become_user: root
  file:
      path: /etc/iptables/rules.v4
      state: absent

- name: ensure iptables rules loaded and restored
  become: yes
  become_user: root
  template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: 0755
      owner: root
      group: root
  with_items:
      - {src: "{{ iptables_rules_path }}", dest: '/etc/iptables.up.rules'}
      - {src: "{{ iptables_rules_recovery }}", dest: '/etc/network/if-pre-up.d/iptables'}
  notify: reload iptables


