---

- name: ensure base tool install
  become: yes
  become_user: root
  apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
  with_items:
      - vim
      - sysstat
      - curl
      - htop
      - iotop
      - apt-transport-https
      - git
      - ca-certificates
      - software-properties-common

- name: ensure sysstart is enable
  become: yes
  become_user: root
  lineinfile:
      dest: /etc/default/sysstat
      state: present
      regexp: 'ENABLED=\"false\"'
      line: 'ENABLED=\"true\"'
  notify: reload sysstat


- include: jenkins.yml
  when: jenkins_bool == "True"

- include: docker.yml
  when: docker_bool == "True"
