---

- name: ensure base tool install
  become: yes
  become_user: root
  apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
  with_items:
      - vim
      - sysstat
      - curl
      - htop
      - iotop
      - apt-transport-https
      - git
      - ca-certificates
      - software-properties-common

- name: ensure sysstart is enable
  become: yes
  become_user: root
  lineinfile:
      dest: /etc/default/sysstat
      state: present
      regexp: 'ENABLED=\"false\"'
      line: 'ENABLED=\"true\"'
  notify: reload sysstat

- name: ensure docker key present
  become: yes
  become_user: root
  apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

- name: add repo
  become: yes
  become_user: root
  apt_repository:
      repo:  deb [arch=amd64] https://download.docker.com/linux/debian    stretch    stable
      state: present

- name: ensure docker install
  become: yes
  become_user: root
  apt:
      name: docker-ce
      state: latest
      update_cache: yes

- name: ensure default editor is vim
  become: true
  become_user: root
  alternatives:
      name: editor 
      link: /usr/bin/vim
      path: /usr/bin/vim.basic
